name: lbnl-resistive-casing

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - jupyterlab>=1.1.0
  - mkl
  - dask
  - geoana==0.0.5
  - pymatsolver==0.1.2
  - discretize==0.4.10
  - SimPEG==0.14.1
  - pip:
    - git+https://github.com/simpeg-research/casingSimulations.git

